window.QUIZ=[
{r:1,q:"¿Qué hibridación tiene el carbono del grupo carbonilo (C=O)?",o:["sp³","sp²","sp","sp³d"],a:1,e:"3 enlaces σ + 1 π: trigonal plana, ~120°."},
{r:1,q:"CH₃CH₂CHO y CH₃COCH₃ son isómeros de…",o:["posición","cadena","grupo funcional","óptica"],a:2,e:"Misma fórmula; uno es aldehído y otro cetona."},
{r:1,q:"¿Qué grupo es +M (resonancia) pero –I (inductivo)?",o:["–CH₃","–NO₂","–OH o halógenos","–COOH"],a:2,e:"Pares libres donan por π; su electronegatividad retira por σ."},
{r:1,q:"¿Por qué un carbocatión terciario es más estable que uno primario?",o:["Más resonancia","Más hiperconjugación (más enlaces σ vecinos)","Hibridación sp","Más dispersión"],a:1,e:"Los enlaces σ C–H/C–C donan densidad al orbital p vacío."},
{r:1,q:"¿Cuál NO es aromática aunque es cíclica y conjugada?",o:["Benceno","Ion ciclopentadienilo","Ciclobutadieno","Piridina"],a:2,e:"4 e⁻ π (4n): antiaromático."},
{r:1,q:"Dos moléculas son imágenes especulares no superponibles. Son…",o:["diastereómeros","enantiómeros","isómeros de posición","confórmeros"],a:1,e:"Definición de enantiómeros."},
{r:1,q:"¿Qué fuerza explica el alto punto de ebullición del agua?",o:["Dispersión de London","Puente de hidrógeno","Efecto inductivo","Ion-dipolo"],a:1,e:"O–H···O intermolecular fuerte."},
{r:1,q:"¿Qué condición NO es necesaria para la aromaticidad de Hückel?",o:["Cíclico","Plano","Exactamente 6 átomos en el anillo","4n+2 e⁻ π deslocalizados"],a:2,e:"Importa el número de e⁻ π, no el tamaño del anillo."},
{r:1,q:"El efecto inductivo se transmite principalmente por enlaces…",o:["π conjugados","σ","de hidrógeno","de coordinación"],a:1,e:"Por σ, y decae rápido con la distancia."},

{r:2,q:"Hibridación de los carbonos del etino (HC≡CH):",o:["sp³","sp²","sp","sp³d²"],a:2,e:"2 enlaces σ y 2 π por carbono: lineal."},
{r:2,q:"¿Qué grupo identifica a un ácido carboxílico?",o:["–CHO","–OH","–CONH₂","–COOH"],a:3,e:"Carbonilo + hidroxilo en el mismo carbono."},
{r:2,q:"cis-2-buteno y trans-2-buteno son isómeros…",o:["de cadena","geométricos","de grupo funcional","de posición"],a:1,e:"Misma conectividad, distinta disposición espacial."},
{r:2,q:"¿Qué efecto estabiliza principalmente al carboxilato RCOO⁻?",o:["Resonancia (carga entre los dos O)","Inductivo de H vecinos","Hiperconjugación","Dispersión"],a:0,e:"La carga negativa se deslocaliza entre ambos oxígenos."},
{r:2,q:"Al alejar el Cl del –COOH (2-cloro → 4-clorobutanoico) la acidez…",o:["aumenta","no cambia","disminuye: el efecto inductivo se atenúa","disminuye por conjugación"],a:2,e:"El –I decae con la distancia por σ."},
{r:2,q:"¿Cuál presenta un sistema conjugado?",o:["Ciclohexano","1,3-butadieno","Butano","Metanol"],a:1,e:"Dobles enlaces alternados, todos sp²."},
{r:2,q:"Entre dos alquenos isómeros, ¿cuál suele ser más estable?",o:["1-buteno","Igual","2-metil-2-buteno (más sustituido)","Depende del disolvente"],a:2,e:"Más hiperconjugación σ→π."},
{r:2,q:"La piridina es aromática con un N con par libre porque…",o:["el N no tiene par libre","el par está en un sp² en el plano, fuera del sistema π","no es plana","tiene 8 e⁻ π"],a:1,e:"Los 6 e⁻ π vienen de los 3 dobles enlaces."},
{r:2,q:"Pentano y hexano: fuerza intermolecular predominante:",o:["Puente de H","Dispersión de London","Dipolo-dipolo","Ion-dipolo"],a:1,e:"Apolares, sin H unido a N/O/F."},

{r:3,q:"Hibridación del N en NH₄⁺:",o:["sp²","sp³","sp","sp³d"],a:1,e:"4 enlaces σ, sin par libre: tetraédrico."},
{r:3,q:"¿Qué grupo une los aminoácidos en el enlace peptídico?",o:["Éster","Amina","Amida","Nitrilo"],a:2,e:"–CONH–."},
{r:3,q:"n-pentano y neopentano (C₅H₁₂) son isómeros de…",o:["cadena","posición","geométricos","enantiómeros"],a:0,e:"Distinto esqueleto carbonado."},
{r:3,q:"El fenol es más ácido que el ciclohexanol por…",o:["inductivo de los H del anillo","resonancia: el fenóxido deslocaliza la carga en el anillo","hiperconjugación","mayor masa molar"],a:1,e:"El ciclohexanol no tiene sistema π."},
{r:3,q:"Cl₃C–COOH es mucho más ácido que CH₃COOH por…",o:["conjugación π","aromaticidad","el fuerte –I de los tres Cl","más H ácidos"],a:2,e:"Estabilizan el carboxilato por σ."},
{r:3,q:"¿Qué explica el color naranja del β-caroteno?",o:["Su masa molar","Su extenso sistema de dobles enlaces conjugados","Hibridación sp³","Puentes de H"],a:1,e:"Conjugación extensa: menor brecha HOMO-LUMO."},
{r:3,q:"Radical más estable:",o:["Metilo","Primario","Terciario","Todos igual"],a:2,e:"Más σ vecinos: hiperconjugación."},
{r:3,q:"El ciclooctatetraeno no es aromático porque…",o:["no es cíclico","no es plano (forma de tina)","tiene 6 e⁻ π","no tiene dobles enlaces"],a:1,e:"Sus orbitales p no se alinean."},
{r:3,q:"Fuerza predominante al disolver NaCl en agua:",o:["Ion-dipolo","Dipolo-dipolo","Solo London","Solo puente de H"],a:0,e:"Iones rodeados por moléculas de agua polares."},

{r:4,q:"Hibridación del carbono cargado (+) del catión alílico:",o:["sp³","sp²","sp","sin orbital p"],a:1,e:"Necesita un p vacío alineado con el π."},
{r:4,q:"El N de la anilina es casi plano (no piramidal) porque…",o:["el anillo desestabiliza sp³","su par se conjuga con el anillo (carácter p)","repulsión estérica","enlace π directo con C ipso"],a:1,e:"Gana resonancia; por eso es mucho menos básica."},
{r:4,q:"Éster y amina en la misma molécula: ¿cuál es el sufijo?",o:["Amina","Éster","Ambos","Ninguno"],a:1,e:"Éster > amina en prioridad IUPAC."},
{r:4,q:"Dos estereocentros; dos isómeros difieren en solo uno. Son…",o:["enantiómeros","diastereómeros","idénticos","constitucionales"],a:1,e:"Enantiómeros difieren en todos los centros."},
{r:4,q:"El ácido tartárico meso es aquiral porque…",o:["no tiene estereocentros","tiene un plano interno de simetría","ambos centros son R","es aromático"],a:1,e:"Su imagen especular es superponible."},
{r:4,q:"Primer criterio CIP para priorizar sustituyentes:",o:["Tamaño del grupo","Número atómico del átomo unido al centro","Polaridad","Longitud de cadena"],a:1,e:"Si hay empate, se avanza al siguiente átomo."},
{r:4,q:"Entre dos estructuras resonantes, contribuye más la…",o:["que tiene separación de carga","que no tiene separación de carga (más enlaces, menos cargas)","ambas siempre igual","ninguna"],a:1,e:"Menor energía, mayor contribución."},
{r:4,q:"El p-nitrofenol es más ácido que el fenol por…",o:["solo inductivo","solo resonante","–I y –M del nitro estabilizando el fenóxido","dispersión"],a:2,e:"Retira densidad por σ y por π."},
{r:4,q:"Hibridación de C2 en CH₂=CH–CH=CH₂:",o:["sp³","sp²","sp","sp³d"],a:1,e:"Todo el sistema conjugado es sp² y plano."},
{r:4,q:"El catión tropilio es aromático porque tiene…",o:["7 e⁻ π","6 e⁻ π (4n+2, n=1)","sin ciclicidad","un C sp³"],a:1,e:"Plano, conjugado, 6 e⁻ π."},
{r:4,q:"e⁻ π deslocalizados del ion ciclopentadienilo:",o:["4","5","6","8"],a:2,e:"4 de los dobles enlaces + par del carbanión."},
{r:4,q:"Aromaticidad de pirrol vs piridina: diferencia clave",o:["N sp³ en pirrol","en el pirrol el par del N está en p y completa 6 π; en la piridina está en sp² en el plano","piridina no aromática","pirrol sin dobles enlaces"],a:1,e:"Cuenta e⁻ π aportados por cada doble enlace."},
{r:4,q:"Un dieno reacciona en cicloadiciones en conformación…",o:["s-trans","s-cis","perpendicular","da igual"],a:1,e:"Alinea ambos extremos del dieno."},
{r:4,q:"Etanol hierve más que dimetil éter (misma masa) porque…",o:["mayor masa","forma puentes de H (tiene O–H)","el éter es más polar","más carbonos"],a:1,e:"El éter no tiene H unido a O."},
{r:4,q:"X–CH₂COOH: el más ácido (solo inductivo)",o:["X = I","X = F","todos igual","X = Br"],a:1,e:"F es el más electronegativo."},
{r:4,q:"Zaitsev: el alqueno más sustituido es más estable por…",o:["resonancia con el disolvente","hiperconjugación σ C–H → π","menor sp²","inductivo de H"],a:1,e:"Más σ adyacentes al doble enlace."},
{r:4,q:"Estereoisómeros máximos con 3 estereocentros (sin meso):",o:["3","6","8","9"],a:2,e:"2ⁿ = 8."},
{r:4,q:"Hückel (4n+2) se formuló originalmente para anillos…",o:["con heteroátomos","monocíclicos","con carga negativa","no planos"],a:1,e:"En naftaleno se aplica de forma extendida (10 e⁻ π)."},
{r:4,q:"1-butanol (117 °C) vs dietil éter (35 °C), ambos C₄H₁₀O:",o:["el éter pesa más","el butanol forma puentes de H; el éter no","el éter es aromático","el butanol es menos polar"],a:1,e:"El éter solo tiene dipolo-dipolo y dispersión."},
{r:4,q:"El –OCH₃ dirige a orto/para porque domina…",o:["solo –I","+M del par libre del O","dispersión","hiperconjugación del CH₃"],a:1,e:"Dona por resonancia al anillo y lo activa."},

{r:5,q:"Catión unido a ciclopropano: un enlace σ C–C se alinea con el p vacío. Es…",o:["resonancia clásica π","hiperconjugación de un σ C–C tensionado","inductivo largo alcance","aromaticidad"],a:1,e:"Un σ dona densidad al orbital p vacío."},
{r:5,q:"Estructuras resonantes equivalentes del catión tropilio:",o:["3","6","7","1"],a:2,e:"La carga puede estar en cualquiera de los 7 C."},
{r:5,q:"N≡C–CH(⁻)–CH=CH₂ deslocaliza la carga porque hay…",o:["C aislado","sistema π continuo (C=C y C≡N conjugados)","N electronegativo sin más","anillo"],a:1,e:"Se requieren orbitales p alineados."},
{r:5,q:"Catión alilo: dos estructuras equivalentes implican que…",o:["carga fija en un C","la carga se reparte por igual en los dos C terminales (~+½)","no hay carga real","carga en el C central"],a:1,e:"Contribuyen igual al híbrido."},
{r:5,q:"Ion fosfato: 3 enlaces P–O equivalentes por resonancia. Longitudes reales:",o:["uno corto y dos largos","los tres iguales, intermedios entre simple y doble","sin longitud definida","solo dos equivalentes"],a:1,e:"El híbrido promedia el carácter de enlace."},
{r:5,q:"En H₃C–CO–NH₂ el par del N se deslocaliza hacia el C=O. Consecuencia:",o:["N más básico que una amina","N mucho menos básico","igual basicidad","depende de la masa"],a:1,e:"El par deslocalizado no acepta protones."},
{r:5,q:"Catión ciclopropenilo (2 e⁻ π). Según Hückel es…",o:["no aromático (anillo de 3)","aromático (4n+2, n=0)","no aromático (carga +)","antiaromático"],a:1,e:"El sistema aromático más pequeño."},
{r:5,q:"Ciclobutadieno (4 e⁻ π, plano, conjugado):",o:["aromático","antiaromático (4n, n=1)","no aromático por no plano","inclasificable"],a:1,e:"Inestable y reactivo."},
{r:5,q:"Dianión ciclobutadienilo (C₄H₄²⁻):",o:["antiaromático","aromático: 6 e⁻ π (n=1)","no aromático por la carga","no cíclico"],a:1,e:"Al añadir 2 e⁻ pasa de 4 a 6 e⁻ π."},
{r:5,q:"Decalino (bicíclico saturado, todo sp³) es…",o:["aromático","no aromático: sin sistema π conjugado","aromático por 10 C","antiaromático"],a:1,e:"Sin orbitales p continuos."},
{r:5,q:"Los 6 e⁻ π del tiofeno vienen de…",o:["solo los 2 dobles enlaces","2 dobles enlaces (4) + un par libre del S en p (2)","pares del S (4) + 2","no es aromático"],a:1,e:"Igual que el pirrol."},
{r:5,q:"En el indol, el par libre del N…",o:["no participa, queda en el plano","forma parte del sistema π aromático (como en el pirrol)","lo vuelve antiaromático","lo hace amina básica típica"],a:1,e:"Por eso el N del indol es poco básico."},
{r:5,q:"Al protonar el N del pirrol vs el de la piridina:",o:["el pirrol pierde la aromaticidad; el piridinio la conserva","ambos la pierden","ambos la conservan","el pirrol la gana"],a:0,e:"En la piridina se protona un par en el plano, fuera del π."},
{r:5,q:"R–CO–O–CO–R' es un…",o:["éster","anhídrido de ácido","cetona","amida"],a:1,e:"Dos carbonilos unidos por un O."},
{r:5,q:"R–CO–X (X = halógeno) es un…",o:["halogenuro de alquilo","haluro de acilo","éter halogenado","ácido carboxílico"],a:1,e:"Halógeno unido al carbono carbonílico."},
{r:5,q:"R–S–S–R' es un…",o:["tioéter","disulfuro","sulfóxido","tiol"],a:1,e:"El enlace S–S lo define."},
{r:5,q:"PH₃ hierve más que SiH₄ (masas similares) porque…",o:["forma puentes de H clásicos","PH₃ es polar (piramidal); SiH₄ es tetraédrico y apolar","SiH₄ tiene más H","es una excepción"],a:1,e:"PH₃ suma dipolo-dipolo a la dispersión."},
{r:5,q:"ICl (97 °C) hierve más que Br₂ (59 °C) porque…",o:["Br₂ es polar","ICl es polar (dipolo permanente); Br₂ es simétrica","el Cl baja el pe","son iguales"],a:1,e:"Dipolo-dipolo + dispersión vs solo dispersión."},
{r:5,q:"Mayor presión de vapor a igual T: octano, pentano, hexano, heptano",o:["Octano","Pentano","Heptano","Todos igual"],a:1,e:"Menor tamaño: dispersión más débil, más volátil."},
{r:5,q:"El catecol (orto) hierve menos que la hidroquinona (para) porque…",o:["el orto forma puente de H intramolecular, con menos puentes intermoleculares","el orto pesa menos","el para no forma puentes de H","el orto es aromático y el para no"],a:0,e:"En para solo hay puentes intermoleculares."}
];
window.EJER=[
"A1. Hibridación del C unido al –OCH₃, del C carbonílico, del O del metoxi y del N de la amida.",
"A2. Nombra los grupos funcionales presentes.",
"A3. Propón un isómero de grupo funcional (no amida) y un isómero de posición.",
"B4. Estructuras resonantes: par libre del N de la amida hacia el C=O.",
"B5. Estructuras resonantes: par libre del O del metoxi hacia el anillo (orto/para).",
"B6. Metoxi: –I vs +M. ¿Activa o desactiva el anillo frente a un electrófilo? ¿Por qué?",
"B7. Compara la basicidad del N de la amida con la de CH₃NH₂.",
"C8. En la 4-metoxicinamida de N-metilo, identifica el sistema conjugado completo.",
"C9. ¿Es más estable el isómero E o el Z? Papel de la hiperconjugación.",
"D10. Tabla de aromaticidad (cíclica, conjugada, e⁻ π, e⁻ libres, total, 4n+2) del imidazol.",
"D11. Los dos N del imidazol: ¿cuál aporta su par al sistema π y cuál es básico?",
"E12. Ordena por punto de ebullición (mayor→menor): ácido 4-metoxibenzoico, amida 1ª, amida 2ª, amida 3ª y éster metílico. Justifica.",
"E13. Cambia –OCH₃ por –NO₂ en el ácido: ¿cómo cambian pe y pKa? Usa inductivo, resonante e IMF."
];
